# -*- coding: utf-8 -*-
"""dissertation2_sentence similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNUmJe2vAl-AGF3MIf5GBUAIdG9hZ4XI
"""

!pip install -q matplotlib scikit-learn

!pip install transformers==4.39.3
!pip install sentence-transformers==2.6.1

"""# context - link similarity (annotation data)"""

import pandas as pd
from sentence_transformers import SentenceTransformer, util
import torch
from tqdm import tqdm

# ✅ 파일 불러오기
file_path = "inversion_ai_nwo.csv"
df = pd.read_csv(file_path)

# ✅ 모델 불러오기
model = SentenceTransformer('all-mpnet-base-v2')

# ✅ cosine similarity 계산 함수
def compute_similarity(row):
    context = row['preceding_discourse']
    link = row['link']

    try:
        context_emb = model.encode(context, convert_to_tensor=True)
        link_emb = model.encode(link, convert_to_tensor=True)
        similarity = util.cos_sim(link_emb, context_emb)[0][0].item()
    except Exception as e:
        similarity = None
    return similarity

# ✅ similarity 계산 후 새로운 열 추가
df['cosine_similarity'] = df.apply(compute_similarity, axis=1)

# ✅ 저장
output_path = "inversion_ai_nwo_cosine.csv"
df.to_csv(output_path, index=False)

# import ace_tools as tools; tools.display_dataframe_to_user(name="Preposing Similarity with Cosine", dataframe=df)

import pandas as pd
from sentence_transformers import SentenceTransformer, util
import torch
from tqdm import tqdm

# ✅ 파일 불러오기
file_path = "passive_human.csv"
df = pd.read_csv(file_path)

# ✅ 모델 불러오기
model = SentenceTransformer('all-mpnet-base-v2')

# ✅ tqdm 설정 (pandas의 apply에 진행 표시)
tqdm.pandas(desc="Computing cosine similarity")

# ✅ cosine similarity 계산 함수
def compute_similarity(row):
    context = row['preceding_discourse']
    link = row['link']

    try:
        context_emb = model.encode(context, convert_to_tensor=True)
        link_emb = model.encode(link, convert_to_tensor=True)
        similarity = util.cos_sim(link_emb, context_emb)[0][0].item()
    except Exception as e:
        similarity = None
    return similarity

# ✅ similarity 계산 후 새로운 열 추가 (진행상황 출력 포함)
df['cosine_similarity'] = df.progress_apply(compute_similarity, axis=1)

# ✅ 저장
output_path = "passive_human_cosine.csv"
df.to_csv(output_path, index=False)

import pandas as pd
from sentence_transformers import SentenceTransformer, util
import torch
from tqdm import tqdm

# ✅ 파일 불러오기
file_path = "passive_ai_context.csv"
df = pd.read_csv(file_path)

# ✅ 모델 불러오기
model = SentenceTransformer('all-mpnet-base-v2')

# ✅ tqdm 설정 (pandas의 apply에 진행 표시)
tqdm.pandas(desc="Computing cosine similarity")

# ✅ cosine similarity 계산 함수
def compute_similarity(row):
    context = row['preceding_discourse']
    link = row['link']

    try:
        context_emb = model.encode(context, convert_to_tensor=True)
        link_emb = model.encode(link, convert_to_tensor=True)
        similarity = util.cos_sim(link_emb, context_emb)[0][0].item()
    except Exception as e:
        similarity = None
    return similarity

# ✅ similarity 계산 후 새로운 열 추가 (진행상황 출력 포함)
df['cosine_similarity'] = df.progress_apply(compute_similarity, axis=1)

# ✅ 저장
output_path = "passive_ai_context_cosine.csv"
df.to_csv(output_path, index=False)

import pandas as pd
from sentence_transformers import SentenceTransformer, util
import torch
from tqdm import tqdm

# ✅ 파일 불러오기
file_path = "passive_ai_nwo.csv"
df = pd.read_csv(file_path)

# ✅ 모델 불러오기
model = SentenceTransformer('all-mpnet-base-v2')

# ✅ tqdm 설정 (pandas의 apply에 진행 표시)
tqdm.pandas(desc="Computing cosine similarity")

# ✅ cosine similarity 계산 함수
def compute_similarity(row):
    context = row['preceding_discourse']
    link = row['link']

    try:
        context_emb = model.encode(context, convert_to_tensor=True)
        link_emb = model.encode(link, convert_to_tensor=True)
        similarity = util.cos_sim(link_emb, context_emb)[0][0].item()
    except Exception as e:
        similarity = None
    return similarity

# ✅ similarity 계산 후 새로운 열 추가 (진행상황 출력 포함)
df['cosine_similarity'] = df.progress_apply(compute_similarity, axis=1)

# ✅ 저장
output_path = "passive_ai_nwo_cosine.csv"
df.to_csv(output_path, index=False)

